# Generated by Django 2.0.5 on 2018-06-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='icon',
            field=models.ImageField(default='default_pictures/male-default.png', upload_to=''),
        ),
    ]
