# Generated by Django 2.0.5 on 2018-06-04 08:45

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='icon',
            field=models.ImageField(default='default_pictures/male-default.png', upload_to=account.models.Account.user_icon_path),
        ),
    ]
