# Generated by Django 2.0.5 on 2018-05-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image1_url',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image2_url',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image3_url',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
