# Generated by Django 2.0.5 on 2018-05-20 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_auto_20180517_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level1_tag', models.CharField(max_length=64)),
                ('level2_tag', models.CharField(max_length=64)),
                ('level3_tag', models.CharField(max_length=64)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_tags', to='main.Article')),
            ],
        ),
    ]
