# Generated by Django 2.0.5 on 2018-06-04 08:45

from django.db import migrations, models
import picture_bed.models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_bed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to=picture_bed.models.Picture.user_pictures_path),
        ),
    ]
