# Generated by Django 2.0.5 on 2018-05-17 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('external_data_access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletext',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_text', to='main.Article'),
        ),
        migrations.AlterField(
            model_name='articletext',
            name='text',
            field=models.TextField(),
        ),
    ]
