# Generated by Django 2.0.5 on 2018-05-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_data_access', '0002_auto_20180518_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletext',
            name='indexed_by_es',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articletext',
            name='indexed_by_solr',
            field=models.BooleanField(default=False),
        ),
    ]
