# Generated by Django 2.0.5 on 2018-09-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_data_access', '0004_auto_20180902_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletext',
            name='indexed_by_es',
        ),
        migrations.RemoveField(
            model_name='articletext',
            name='indexed_by_solr',
        ),
    ]
